#KBOOTCONFIG
; Xbox 360 Arch Linux boot configuration
; Adjust maxcpus as needed (1-6). Start with 2 for stability.
;
; Video modes:
;  0: VGA_640x480     7: VGA_1280x720
; 10: HDMI_720P      11: YUV_720P
;videomode=10
speedup=1
timeout=30

archlinux="usb:/vmlinux root=PARTUUID=d88ce1fb-03 rootfstype=ext4 console=tty0 panic=60 maxcpus=6 coherent_pool=16M rootwait video=xenosfb init=/sbin/xenon-rescue-init"
archlinux_safe="usb:/vmlinux root=PARTUUID=d88ce1fb-03 rootfstype=ext4 console=tty0 panic=60 maxcpus=2 coherent_pool=16M rootwait video=xenosfb init=/sbin/xenon-rescue-init"
archlinux_systemd="usb:/vmlinux root=PARTUUID=d88ce1fb-03 rootfstype=ext4 console=tty0 panic=60 maxcpus=6 coherent_pool=16M rootwait video=xenosfb"
archlinux_systemd_safe="usb:/vmlinux root=PARTUUID=d88ce1fb-03 rootfstype=ext4 console=tty0 panic=60 maxcpus=2 coherent_pool=16M rootwait video=xenosfb single"
